### PR TITLE
Feat/add-golang-lint

### PR DESCRIPTION
**Pull request by nerdeveloper**
related to https://github.com/helm/chartmuseum/issues/569

### CODE REVIEW

**Review by cbuto — APPROVED** [review]
looks great! 🚀 

You'll need to sign the commits before merging though!

**Comment by cbuto** [comment]
> @cbuto I am confused; my commits are signed, and DCO did not throw any error. Kindly assist me. Screenshot 2022-09-19 at 17 37 03

You have to setup a key that will be used for [signing commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits), there are some docs [here](https://docs.github.com/en/authentication/managing-commit-signature-verification/generating-a-new-gpg-key) that describe how to generate a new key and setup git to sign commits with that key. 

It's required in addition to the DCO signoff.

**Comment by nerdeveloper** [comment]
Hey, @scbizu, Can I go ahead and merge this PR? I wanted to take a look at it before merging.

**Comment by scbizu** [comment]
@nerdeveloper Please do the `rebase -i` stuff , the merge requires all commits are verified.

**Comment by nerdeveloper** [comment]
@scbizu done

**Pull request merged**
