### PR TITLE
Add per chart limit option

### LINKED ISSUE #376: Is there a way to limit number of old charts?
Is there currently any way to limit number of old charts cumulating over time?

There was some idea to do this back in 2018: https://github.com/helm/chartmuseum/pull/135 but looks like it was never finished.

### PR DESCRIPTION
**Pull request by scbizu**
impls #316 

Also , closes #376 

- [x] backend storage and index cache supports per chart limit

Maybe in next release:

-  lock chart to be unremovable
-  provide a dry run command to clean museum(per chart) , also works with chart lock mechanism

### CODE REVIEW

**Comment by scbizu** [comment]
I found a problem during implementing this feature , dose all of our storage impls support the same name file covering. With the #454 , we can now update our cache index in the chart updating case , but it still can be stored into backend storage if this backend storage do not support the same name file covering or add some other more suffixes into the package name . 

However, we maybe break the above case and the `per-chart-limit` option will also limit the same name artifact at N versions . I do not know if this should be mentioned in the next release note.

**Comment by jdolitsky** [comment]
@scbizu - where do we stand with this and #457 ?

**Comment by jdolitsky** [comment]
@scbizu can you rebase?

**Comment by scbizu** [comment]
done @jdolitsky

**Review by jdolitsky — APPROVED** [review]

**Pull request merged**
