### PR TITLE
feat: allow user set forcePathStyle for s3 storage

### PR DESCRIPTION
**Pull request by warjiang**
!!! Note: This PR depends on the merger of [another PR](https://github.com/chartmuseum/storage/pull/906) to be merged. We have mentioned a PR in chartmuseum/storage to support users to manually set `s3ForcePathStyle`. After the pr of storage is merged, I will remove the WIP status of the current PR.

This PR mainly provides support for command line parameters, allowing users to set s3ForcePathStyle through command line parameters.

If possible, anyone can help me review the PR in chartmuseum/storage.
thks

### CODE REVIEW

**Comment by warjiang** [comment]
somthing wrong with git(dco not works with ssh ), still make dco finally

**Comment by scbizu** [comment]
@warjiang Hi , we just release the storage v0.14.1 , can you fix your `go.mod`  ?

**Comment by warjiang** [comment]
> @warjiang Hi , we just release the storage v0.14.1 , can you fix your `go.mod` ?

@scbizu Alreay update the dependencies of the `chartmuseum` and resolve the WIP status.  Also update usage of new options of amazon-storage in the README.md. BTW thank you very much for your quick response ⚡

**Review by scbizu — APPROVED** [review]

**Comment by scbizu** [comment]
@cbuto PTAL

**Comment by warjiang** [comment]
can anyone help to merge this pr, i want to use official chartmuseum instead of self build, thks

**Comment by scbizu** [comment]
@warjiang try our canary image when action ready .

**Pull request merged**
