### PR TITLE
prepare for v0.13.0 release

### LINKED ISSUE #391: Migrate release process to follow Helm's
Should adopt Makefile and release flow, and migrate from:

- Custom S3 bucket to get.helm.sh
- Docker Hub to GitHub registry

Releases should be signed, and should be able to install chartmuseum with install script similar to Helm's

### PR DESCRIPTION
**Pull request by jdolitsky**
- update to Go 1.15.7
- add release artifacts script (copied from Helm)
- add KEYS file containing maintainer signing keys
- update Makefile to follow Helm release process
- update dependencies (including auth and storage)
- rename masterHandler to rootHandler
- add get-chartmuseum script (based on get-helm-3 script)
- remove unused scripts and make targets for old release process
- modify README with new install instructions and docker image
- rename scripts to use dashes vs underscores

Fixes #391 and #404

### CODE REVIEW

**Comment by scbizu** [comment]
Why not rm the `_dist` directory after built the artifact ? I see the .gitignore file but remove the _dist dir is better ?

**Comment by jdolitsky** [comment]
@scbizu - this can be deleted with `make clean` (along with other files)

**Comment by scbizu** [comment]
OK I see . Thank you . 

And if we can use another official github container registry secret name rather than my test secret name XD ?

**Comment by scbizu** [comment]
👍  Looks good to me now

**Review by scbizu — APPROVED** [review]

**Pull request merged**
