### PR TITLE
Upgrade helm version to 2.14.3

### LINKED ISSUE #269: Upgrade to Helm 2.14.3
In libs and test

### PR DESCRIPTION
**Pull request by prabhu43**
Fixes #269

### CODE REVIEW

**Comment by karuppiah7890** [comment]
cc @jdolitsky

**Comment by davidovich** [comment]
I believe there are some missing changes in:

(scripts/setup_test_environment.sh)[https://github.com/helm/chartmuseum/blob/35ade03a8e43b8e1fb13404477fe6dffb245bcef/scripts/setup_test_environment.sh]

**Comment by prabhu43** [comment]
@davidovich Fixed the helm version in `scripts/setup_test_environment.sh`. Please check now

**Pull request merged**
