### PR TITLE
WIP: Testing out lint job on pipeline

### PR DESCRIPTION
**Pull request by hydeenoble**
Signed-off-by: Idowu Emehinola <hydeenoble39@gmail.com>

### CODE REVIEW

**Comment by hydeenoble** [comment]
cc: @nerdeveloper: 
image

**Comment by cbuto** [comment]
@hydeenoble before we include linting in our CI checks, we need to resolve a few existing linting errors. This PR would be the last step in the process 😄

**Comment by hydeenoble** [comment]
> @hydeenoble thanks for working on this! Before we include linting in our CI checks, we need to resolve a few existing linting errors. This PR would be the last step in the process 😄

Alright, @cbuto I can always hold off on this till we are ready.

**Comment by cbuto** [comment]
@hydeenoble a PR is definitely still welcome for the GitHub action! We will still definitely need it

**Comment by jdolitsky** [comment]
closing as outdated

**Pull request closed without merging**
