### PR TITLE
Added --history-limit option.

### PR DESCRIPTION
**Pull request by aleerizw**
Old chart versions are deleted when a chart is added

Implements https://github.com/kubernetes-helm/chartmuseum/issues/134

### CODE REVIEW

**Comment by aleerizw** [comment]
@davidovich Please let me know if there are any changes required. Thanks!

**Comment by jdolitsky** [comment]
hi @aleerizw we will try to get this merged this week, thanks for your patience

**Comment by davidovich** [comment]
@aleerizw sorry for the silence, work was keeping me very busy last week. 

I am a bit uneasy on the point of adding a deletion process to an add operation (uploadChartPackage).

Could we envision starting a goroutine at server startup time that collects older charts and does the house keeping? We could trigger/control the house keeping in a channel from the `uploadChartPackage` function.

What do you think ?

**Comment by jdolitsky** [comment]
We do need some sort of background task management in general.

**Comment by aleerizw** [comment]
I agree, I was not sure about this myself as well but wanted to get something out quickly :) I will make the changes

**Pull request closed without merging**
