### PR TITLE
Improve performance when dealing with  thousands of charts

### LINKED ISSUE #332: Performance downgrade when dealing with thousands of charts
## Background
In our use case, it's easy to generate thousands of charts within couple weeks because CI/CD pipeline is integrated with hundreds of GitHub repositories and each pipeline run generates one chart.

Per observation, **It takes more than 10s to response any API (e.g. `GET /api/charts/<name>`) if there are about 5000 charts.**. Performance downgrade is dramatic and unacceptable. Especially when working together with Harbor, it makes the call to harbor frequently fail due to a fixed timeout interval (10s in this case).

## Analysis
All the `GET` requests call function `getIndexFile()`, which searches all the chart files from storage and updates the cache for `index.yaml` regardless whether the cache exists or not. It performs slower and slower with the growth of chart numbers. Although consistency and real-time are guaranteed, cache seems don't work at all.

## Proposal
To solve the problem and improve the performance, the only way is to make the cache "work" as expected. Therefore, I recommend to apply the following changes,
- Always read from cache in function `getIndexFile()` without traversing the files on the disk. If cache is missing, rebuild it
- Delta update the cache in all the WRITE requests (e.g. `POST /api/charts` or `DELETE /api/charts/<name>/<version>`)
- Delta update the cache every 5min (in case the files on the disk are manually manipulated)

A PR will be provided to fix the issue in 2 weeks. Hope some one from the governance team can review and accept it.

### PR DESCRIPTION
**Pull request by wulou**
## Summary

As we have disscsused in the [issue](#332),  we need to improve the performance when  dealing with  thousands of charts.  Therefor, we made some changes as we proposed before. 

##  Changes

- Always read from cache in function getIndexFile() without traversing the files on the disk. If cache is missing, rebuild it
- Delta update the cache in all the WRITE requests (e.g. POST /api/charts or DELETE /api/charts/<name>/<version>)
- Delta update the cache every 5min (in case the files on the disk are manually manipulated)

fixes #332

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* One or more commits are not associated with a GitHub user. The email used in the Git commit must match a verified email address in a GitHub user profile. For more information, please see https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/

_Regards,
CLA GitHub bot_

**Comment by jdolitsky** [comment]
@wulou - wow, thanks. Could you please fix the DCO issue and ensure the unit tests are passing?

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* One or more commits are not associated with a GitHub user. The email used in the Git commit must match a verified email address in a GitHub user profile. For more information, please see https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/

_Regards,
CLA GitHub bot_

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* One or more commits are not associated with a GitHub user. The email used in the Git commit must match a verified email address in a GitHub user profile. For more information, please see https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/

_Regards,
CLA GitHub bot_

**Comment by wulou** [comment]
retrigger

**Comment by Ailsa-Wu** [comment]
I'm so sorry to close this PR because of CLA. I have create new one with a new github account (signing in with my work e-mail).  Please review it [339](https://github.com/helm/chartmuseum/pull/339). Thanks!

**Pull request closed without merging**
