### PR TITLE
Add support for TLS client certificate auth

### PR DESCRIPTION
**Pull request by amerghazal**
Hello,

This is my first PR to this project. It addresses #79 by adding support for TLS client certificate authentication. Looking forward to your feedback - thank you! Example:

Server:
```
% bin/darwin/amd64/chartmuseum --debug --port=8443 --storage="local" \
--storage-local-rootdir=".chartstorage/" \
--tls-ca-cert certs/ca.pem \
--tls-key certs/server.key \
--tls-cert certs/server.pem
2019-01-10T12:21:40.331-0600	DEBUG	Fetching chart list from storage	{"repo": ""}
2019-01-10T12:21:40.331-0600	DEBUG	No change detected between cache and storage	{"repo": ""}
2019-01-10T12:21:40.331-0600	INFO	Starting ChartMuseum	{"port": 8443}
2019-01-10T12:21:45.712-0600	DEBUG	[1] Incoming request: /api/charts	{"reqID": "2911353b-9ed7-4640-92eb-ffd96c22bc99"}
2019-01-10T12:21:45.712-0600	DEBUG	[1] Adding package to storage	{"package": "mychart-0.1.0.tgz", "reqID": "2911353b-9ed7-4640-92eb-ffd96c22bc99"}
2019-01-10T12:21:45.713-0600	INFO	[1] Request served	{"path": "/api/charts", "comment": "", "latency": "987.6µs", "clientIP": "::1", "method": "POST", "statusCode": 201, "reqID": "2911353b-9ed7-4640-92eb-ffd96c22bc99"}
http: TLS handshake error from [::1]:57399: tls: client didn't provide a certificate
^C
```

Client:
```
% curl -k --data-binary "@testdata/charts/mychart/mychart-0.1.0.tgz" \
--key certs/client.key \
--cert certs/client.pem \
https://localhost:8443/api/charts
{"saved":true}%                                                                                                                                                                                                 
% curl -k --data-binary "@testdata/charts/mychart/mychart-0.2.0.tgz" \
https://localhost:8443/api/charts
curl: (35) error:1401E412:SSL routines:CONNECT_CR_FINISHED:sslv3 alert bad certificate
```

Certificates:
```
% openssl x509 -in certs/server.pem -noout -issuer -serial -fingerprint
issuer= /C=DE/ST=NRW/L=Earth/O=Random Company/OU=IT/CN=www.random.com/emailAddress=test@test.com
serial=A5E4A9A07340320D
SHA1 Fingerprint=18:C5:33:B2:97:F5:D8:D7:5A:08:69:E3:87:16:32:0F:F7:2B:BB:C3
% openssl x509 -in certs/client.pem -noout -issuer -serial -fingerprint
issuer= /C=DE/ST=NRW/L=Earth/O=Random Company/OU=IT/CN=www.random.com/emailAddress=test@random.com
serial=02
SHA1 Fingerprint=5C:D2:E6:39:70:EB:DF:5B:0C:A5:A7:16:A7:6C:61:9E:8E:DE:03:91
% openssl x509 -in certs/ca.pem -noout -issuer -serial -fingerprint
issuer= /C=DE/ST=NRW/L=Earth/O=Random Company/OU=IT/CN=www.random.com/emailAddress=test@random.com
serial=9A729D2C0A78C1E1
SHA1 Fingerprint=B8:BD:9D:60:76:4A:7F:B4:BE:7E:25:4B:39:B1:A3:CF:43:51:EF:A2
```

### CODE REVIEW

**Comment by amerghazal** [comment]
thanks

1. as far as i can tell it doesn't seem to be possible - sugaredlogger doesn't implement log.Logger which is what http.Server accepts for logging
2. will do!

**Comment by jdolitsky** [comment]
lgtm!

**Pull request merged**
