### PR TITLE
when depth<0, the length of repo is variable

### PR DESCRIPTION
**Pull request by wutongjie23hao**
in fact, the length of depth is variable. So it's necessary.

### CODE REVIEW

**Comment by jdolitsky** [comment]
@wutongjie23hao Hello, could you please explain the change a little more?

**Comment by wutongjie23hao** [comment]
@jdolitsky Hello, when depth==-1 , the length of repo may vary, may be 1,2 or 3. It's usefull when multi-tenants .

**Comment by jdolitsky** [comment]
@wutongjie23hao ah i see. thank you for explaining.

Can we please then create a boolean flag to handle this `--depth-dynamic` that causes `--depth` to be ignored? Can you also please add tests in match_test.go?

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* One or more commits are not associated with a GitHub user. The email used in the Git commit must match a verified email address in a GitHub user profile. For more information, please see https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/

_Regards,
CLA GitHub bot_

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* One or more commits are not associated with a GitHub user. The email used in the Git commit must match a verified email address in a GitHub user profile. For more information, please see https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/

_Regards,
CLA GitHub bot_

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* One or more commits are not associated with a GitHub user. The email used in the Git commit must match a verified email address in a GitHub user profile. For more information, please see https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/

_Regards,
CLA GitHub bot_

**Comment by wutongjie23hao** [comment]
@jdolitsky hello , --depth-dynamic args have been added. Also, i modified match_test to add test case of depth dynamic.

**Comment by jdolitsky** [comment]
@wutongjie23hao sorry for the long delay. this looks good to me. merging!

**Pull request merged**
