### PR TITLE
feat(router): add support for CORS Access-Control-Allow-Origin header

### PR DESCRIPTION
**Pull request by johanfleury**

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @johanfleury isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @johanfleury isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by johanfleury** [comment]
I signed the CLA.

**Comment by johanfleury** [comment]
I signed the CLA.

**Comment by jdolitsky** [comment]
@johanfleury sorry for the delay. this looks good. just having some issue w CI at this point, will get this in shortly

**Comment by johanfleury** [comment]
Thank you very much :)

**Pull request merged**
