### PR TITLE
feat(jmespath): add jmespath support

### PR DESCRIPTION
**Pull request by marcoklaassen**
# JMESPath Support

Not every JWT token provider is able to define the token the way the chartmuseum wants it. 
In my case, my sso produces e.g.:

```
"resource_access": {
    "chartmuseum": {
      "roles": [
        "pull"
      ]
    }
  },
```
If you are not able to configure the JWT token provider yourself, i think it is a good idea to provide a solution by the chartmuseum. 

With JMESPath Support we can make the path to find the allowed actions configurable.
To avoid a breaking change, i defined a default JMESPath in the auth module. This default configuration does the same job as the old implementation. 

The pull request for the auth repository: https://github.com/chartmuseum/auth/pull/10

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @marcoklaassen isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by marcoklaassen** [comment]
I signed it

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @marcoklaassen isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @marcoklaassen isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @marcoklaassen isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by jdolitsky** [comment]
Cool feature, thank you. Putting this into a v0.14 milestone since we are behind on getting v0.13 out

**Review by jdolitsky — APPROVED** [review]

**Pull request merged**
