### PR TITLE
Adding cifs-utils to the apk add RUN line 

### PR DESCRIPTION
**Pull request by fabiendibot**
Hi,

In order to have the alpine image mount cifs volume this package is needed. Adding this few words, we could use services like Azure File Share.

Regards,

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* One or more commits are not associated with a GitHub user. The email used in the Git commit must match a verified email address in a GitHub user profile. For more information, please see https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/

_Regards,
CLA GitHub bot_

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @fabiendibot isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by jdolitsky** [comment]
@fabiendibot sorry for the delay here.

I'm hesitant to add more to the Docker image to support a specific vendor. Could you explain more about the issue? Are you running this via Kubernetes?

**Comment by jdolitsky** [comment]
@fabiendibot ok, sounds good.

Please fix merge conflict, as well as the missing `]` character in `ENTRYPOINT ["/chartmuseum"` and will go ahead and merge

**Comment by jdolitsky** [comment]
@fabiendibot this change is now in `chartmuseum/chartmuseum:latest`, please try and let us know that this works as expected

**Pull request merged**
