### PR TITLE
Add --log-latency-integer option

### LINKED ISSUE #321: Latency value from Chartmuseum logs
Hey all,

The `latency` value (for example `latency: 520.816056ms`) returned by the logs still has the units in it's string, which when ingested in Elasticsearch cause some conflicts (string vs int) with others go software that write the `latency` values with a int type.

I know that I could use some mapping within Kibana to modify the values of the logs to a int.
But mainly this issue is more of a proposal instead of a issue with the software.

Proposal: Modifying [this](https://github.com/helm/chartmuseum/blob/master/pkg/chartmuseum/router/middleware.go#L55) line to this: `"latency", int64(time.Now().Sub(start)),`

One of the main drawbacks of changing it from a string to a int is that it is _less_ human readable.

I'm happy to create a PR if you guys agree with this. If not you can just close this issue.

Thanks

### PR DESCRIPTION
**Pull request by Retenodus**
Fix #321

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* One or more commits are not associated with a GitHub user. The email used in the Git commit must match a verified email address in a GitHub user profile. For more information, please see https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/

_Regards,
CLA GitHub bot_

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* One or more commits are not associated with a GitHub user. The email used in the Git commit must match a verified email address in a GitHub user profile. For more information, please see https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/

_Regards,
CLA GitHub bot_

**Comment by Retenodus** [comment]
CLA GitHub bot verify

**Comment by Retenodus** [comment]
CLA GitHub bot verify

**Pull request merged**
