### PR TITLE
etcd support added

### PR DESCRIPTION
**Pull request by debarshibasak**

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @debarshibasak isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by jdolitsky** [comment]
@debarshibasak this looks great! Would you mind adding a small section to the readme on how to use?

**Comment by debarshibasak** [comment]
I updated flags. I will update Readme now.

**Comment by jdolitsky** [comment]
@debarshibasak thank you. ready for merge?

**Comment by debarshibasak** [comment]
It is ready to merge. Thanks

**Pull request merged**
